### ISSUE TITLE
有没有办法通过Maven依赖的形式引入最新稳定的版本？另外给以详细的集成和使用使用步骤？

### ISSUE THREAD

**Issue by angelyouyou** [hjx601496320/plumber#6]
有没有办法通过Maven依赖的形式引入最新稳定的版本？

**Comment by hjx601496320** [comment]
maven 引入 不太行 因为读取binlog 需要开启一个新的线程，你可以把 core 包里的东西复制出来自己修改一下。
使用的话，就是按照readme 来操作就好了 或者加qq 601496320
