### ISSUE TITLE
如何在同步到目标数据库前得到对象数据？有时需要在落地之前做一些其它事情？

### ISSUE THREAD

**Issue by angelyouyou** [hjx601496320/plumber#7]
如何在同步到目标数据库前得到对象数据？有时需要在落地之前做一些其它事情？

**Comment by hjx601496320** [comment]
同步到目标数据库前得到对象数据  这个是指？对象的数据结构？表结构 还是？

**Comment by angelyouyou** [comment]
> 同步到目标数据库前得到对象数据 这个是指？对象的数据结构？表结构 还是？

@hjx601496320 希望在落地前得到这个对象或表结构，最终是想做一些自己的业务处理，在落地前。

**Comment by hjx601496320** [comment]
这个是在启动项目的时候 获取的表的数据结构，在TableMateData 这个类里面，在每个binlog事件里会有一个 tableid ，可以通过这个获取每次binlog 改动的是哪一个表

**Comment by angelyouyou** [comment]
@hjx601496320 多谢
